### ISSUE TITLE
feat(fixtures): Hardfork Execution Test Fixtures

### ISSUE THREAD

**Issue by refcell** [ethereum-optimism/tests#43]
**Description**

With the `opt8n` tool successfully generating execution test fixtures in the `fixtures/execution/` directory, the next step is to generate a bunch of test fixtures and document the process along the way.

This ticket is to generate execution test fixtures surrounding the various network upgrades aka hardforks.
To properly test hardfork execution behavior, we need test fixtures that assert correct behavior both prior to the hardfork and after it's enabled.

Hardforks (listed in [specs.optimism.io](https://specs.optimism.io))
- [Regolith](https://specs.optimism.io/protocol/regolith/overview.html)
- [Canyon](https://specs.optimism.io/protocol/canyon/overview.html)
- [Delta](https://specs.optimism.io/protocol/delta/overview.html)
- [Ecotone](https://specs.optimism.io/protocol/ecotone/overview.html)
- [Fjord](https://specs.optimism.io/fjord/overview.html)

**Comment by 0xForerunner** [comment]
Currently blocked by https://github.com/foundry-rs/foundry/pull/8749

Will come back to this when that's merged in.
